version: 2

jobs:
  vulnerability_scan:
    docker:
      - image: docker:18.09.1-git
    environment:
      DOCKER_IMAGE: dgoeke/clair-poc
    working_directory: /app
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Building application Docker image
          command: docker build -t $DOCKER_IMAGE .
      - run:
          name: Scanning application Docker image
          command: |
            docker network create scanning
            docker run -p 5432:5432 -d --net=scanning --name db arminc/clair-db:latest
            docker run -p 6060:6060  --net=scanning --link db:postgres -d --name clair arminc/clair-local-scan:v2.0.6
            docker run --net=scanning --rm --name=scanner --link=clair:clair -v '/var/run/docker.sock:/var/run/docker.sock'  objectiflibre/clair-scanner --clair="http://clair:6060" --ip="scanner" -t Medium $DOCKER_IMAGE

  compliance_scan:
    docker:
      - image: docker:18.09.1-git
    environment:
      DOCKER_IMAGE: dgoeke/clair-poc
    working_directory: /app
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Building application Docker image
          command: docker build -t $DOCKER_IMAGE .
      - run:
          name: Build scanner image with custom InSpec profiles
          command: docker build -t my-inspec ./inspec
      - run:
          name: Scanning application Docker image
          command: |
            docker run --detach --name app $DOCKER_IMAGE
            docker run --name=scanner -v '/var/run/docker.sock:/var/run/docker.sock' my-inspec exec profiles/sample -t docker://app

workflows:
  version: 2
  workflow:
    jobs:
      - vulnerability_scan
      - compliance_scan
