version: 2

jobs:
  build:
    docker:
      - image: docker:18.09.1-git
    environment:
      DOCKER_IMAGE: dgoeke/clair-poc
    working_directory: /app
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build application Docker image
          command: docker build --cache-from=app -t $DOCKER_IMAGE .
      - run:
          name: Scanning image
          command: |
            docker network create scanning
            docker run -p 5432:5432 -d --net=scanning --name db arminc/clair-db:latest
            docker run -p 6060:6060  --net=scanning --link db:postgres -d --name clair arminc/clair-local-scan:v2.0.6
            docker run --net=scanning --rm --name=scanner --link=clair:clair -v '/var/run/docker.sock:/var/run/docker.sock'  objectiflibre/clair-scanner --clair="http://clair:6060" --ip="scanner" -t Medium $DOCKER_IMAGE

workflows:
  version: 2
  workflow:
    jobs:
      - build
