version: 2

jobs:
  build_image:
    docker:
      - image: docker:18.09.1-git
    environment:
      DOCKER_IMAGE: dgoeke/clair-poc
    working_directory: /app
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Building application Docker image
          command: docker build -t $DOCKER_IMAGE .
      - run:
          name: Save image to an archive
          command: |
            mkdir docker-image
            docker save -o docker-image/image.tar $DOCKER_IMAGE
      - persist_to_workspace:
          root: .
          paths:
            - docker-image

  vulnerability_scan:
    docker:
      - image: docker:18.09.1-git
    environment:
      DOCKER_IMAGE: dgoeke/clair-poc
    working_directory: /app
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: workspace
      - run:
          name: Load image
          command: |
            docker load --input workspace/docker-image/image.tar
      - run:
          name: Scanning application Docker image
          command: |
            docker network create scanning
            docker run -p 5432:5432 -d --net=scanning --name db arminc/clair-db:latest
            docker run -p 6060:6060  --net=scanning --link db:postgres -d --name clair arminc/clair-local-scan:v2.0.6
            docker run --net=scanning --rm --name=scanner --link=clair:clair -v '/var/run/docker.sock:/var/run/docker.sock'  objectiflibre/clair-scanner --clair="http://clair:6060" --ip="scanner" -t Medium $DOCKER_IMAGE

  compliance_scan:
    docker:
      - image: docker:18.09.1-git
    environment:
      DOCKER_IMAGE: dgoeke/clair-poc
    working_directory: /app
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: workspace
      - run:
          name: Load image
          command: |
            docker load --input workspace/docker-image/image.tar
      - run:
          name: Build scanner image with custom InSpec profiles
          command: docker build -t my-inspec ./inspec
      - run:
          name: Scanning application Docker image
          command: |
            docker run --detach --name app $DOCKER_IMAGE
            docker run --name=scanner -v '/var/run/docker.sock:/var/run/docker.sock' my-inspec exec profiles/sample -t docker://app

  publish_image:
    docker:
      - image: circleci/python:3.6.1
    environment:
      AWS_DEFAULT_OUTPUT: json
      ECR_REPOSITORY_NAME: testapp
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: workspace
      - run:
          name: Install AWS CLI
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip3 install awscli
      - run:
          name: Load image
          command: |
            docker load --input workspace/docker-image/image.tar
      - run:
          name: Push image to ECR
          command: |
            . venv/bin/activate
            eval $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
            docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$ECR_REPOSITORY_NAME:$CIRCLE_SHA1

workflows:
  version: 2
  workflow:
    jobs:
      - build_image
      - vulnerability_scan:
          requires:
            - build_image
      - compliance_scan:
          requires:
            - build_image
      - publish_image:  # TODO requires: vulnerability & compliance, filters:branches:only:master
          requires:
            - build_image
